version: "3"
services:
  
  hajjs_service:
    build: ./hajjs_service
    container_name: hajjs_service_container
    ports:
      - "5000:5000"
    networks:
      - ecommerce-app
    links:
      - hajjs_db
    restart: on-failure
    depends_on:
      - hajjs_db
    volumes:
      - ./hajjs_service:/app
      - /app/node_modules
  hajjs_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - ecommerce-app
    volumes:
      - hajjs-volume:/data/db
  omras_service:
    build: ./omras_service
    container_name: omras_service_container
    ports:
      - "5001:5001"
    networks:
      - ecommerce-app
    links:
      - omras_db
    restart: on-failure
    depends_on:
      - omras_db
    volumes:
      - ./omras_service:/app
      - /app/node_modules
  omras_db:
    image: mongo:3.6.19-xenial
    ports:
      - "27018:27017"
    networks:
      - ecommerce-app
    volumes:
      - omras-volume:/data/db

networks:
  ecommerce-app:
    driver: bridge
volumes:
  hajjs-volume:
    driver: local
  omras-volume:
    driver: local
 
